### ISSUE TITLE
Cleanup `alt-src` staging directories

### ISSUE THREAD

**Issue by siteshwar** [CentOS/sync2git#13]
`alt-src` script uses several directories to stage content before pushing it. We should regularly clean these directories to avoid any conflicts/failures with `alt-src` pushes (those could be hard to debug).

**Comment by james-antill** [comment]
So I think we can just use "-o stagedir=\<tmpdir>/stage -o gitdir=\<tmpdir>/git -o lookaside=\<tmpdir>/lookaside" on all our alt-src calls, where tmpdir is trules temporary for this run of the program (getting deleted afterwards).

This would add a little bit to the runtime, but only for packages/modules that need pushing.

But I'd be happy if you and @bstinsonmhk would say this is fine too, before I do a patch.

**Comment by siteshwar** [comment]
> So I think we can just use "-o stagedir=<tmpdir>/stage -o gitdir=<tmpdir>/git -o lookaside=<tmpdir>/lookaside" on all our alt-src calls, where tmpdir is trules temporary for this run of the program (getting deleted afterwards).

Sounds good to me. If the push fails, the directory should be retained for debugging purpose.
